joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 60

joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints: 
    - Cat_740_Dumper_Joint
    - Cat_740_DumperHolder_Joint
    - Cat_740_DumperCylinderLeft_Joint
    - Cat_740_DumperCylinderRight_Joint
    - Cat_740_SteeringCylinderLeft_Joint
    - Cat_740_SteeringCylinderRight_Joint
    - Cat_740_DumperPistonLeft_Joint
    - Cat_740_DumperPistonRight_Joint
    - Cat_740_DumperPistonHeadLeft_Joint
    - Cat_740_DumperPistonHeadRight_Joint
    - Cat_740_SteeringPistonLeft_Joint
    - Cat_740_SteeringPistonRight_Joint